server:
  port: 8080
spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: DevNote
  datasource:
    url: jdbc:postgresql://localhost:5433/dev_note
    username: dev
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
jwt:
  secret: ${JWT_SECRET}
  expiration-seconds: 3600
logging:
  level:
    dev.project: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
